<CustomDropDown>
	gridLayoutClip: gridlayout_clip
	gridlayoutDownloadFailedVideos: gridlayout_downloadFailedVideos
	gridlayoutRenameFailedVideos: gridlayout_renameFailedVideos
	gridLayoutShare: gridlayout_share
	gridLayoutSettings: gridlayout_settings
	gridLayoutDelete: gridlayout_delete
	gridLayoutDownHisto: gridlayout_downloadHisto
	gridLayoutChangePlaylist: gridlayout_changePlaylist
	saveButton: save_Button

    # defining canvas causes disabled drop down menu items to be
    # low grayed instead of being transparent !
    canvas.before:
        Color:
            rgb: [0.22,0.22,0.22]
        Rectangle:
            pos: self.pos
            size: self.size

	Button:
		text: 'Load'
		size_hint_y: None
		height: '28dp'
		on_release: root.showLoad()
	Button:
		id: save_Button
		text: 'Save'
		size_hint_y: None
		height: '28dp'
		disabled: True
		on_release: root.showSave()
    GridLayout: # enable to hide or display 'Delete' menu item
        id: gridlayout_delete
		cols: 1
        size_hint_y: None
        height: "0dp"
        Button:
            id: delete_Button
            text: 'Delete'
            size_hint_y: None
            height: '28dp'
            on_release: root.showDelete()
    GridLayout: # enable to hide or display 'Clip audio' menu item
        id: gridlayout_clip
		cols: 1
        size_hint_y: None
        height: "0dp"
        Button:
            text: 'Clip audio'
            size_hint_y: None
            height: '28dp'
            disabled: False
            on_release: root.showClipAudioFile()
    GridLayout: # enable to hide or display 'Share audio' menu item
        id: gridlayout_share
		cols: 1
        size_hint_y: None
        height: "0dp"
        Button:
            id: shareAudioFile_Button
            text: 'Share audio'
            size_hint_y: None
            height: '28dp'
            disabled: False
            on_release: root.shareAudio()
    GridLayout: # enable to hide or display 'Download failed videos' menu item
        id: gridlayout_downloadFailedVideos
		cols: 1
        size_hint_y: None
        height: "0dp"
        Button:
            id: downloadFailedVideos_Button
            text: 'Down failed vids'
            size_hint_y: None
            height: '28dp'
            disabled: False
            on_release: root.handleFailedVideosDownloading()
    GridLayout: # enable to hide or display 'Rename failed videos' menu item
        id: gridlayout_renameFailedVideos
		cols: 1
        size_hint_y: None
        height: "0dp"
        Button:
            id: renameFailedVideos_Button
            text: 'Rename failed vids'
            size_hint_y: None
            height: '28dp'
            disabled: False
            on_release: root.renameFailedVideosUpdatedFromPC()
    GridLayout: # enable to hide or display 'Down histo' menu item
        id: gridlayout_downloadHisto
		cols: 1 
        size_hint_y: None
        height: "0dp"
        Button:
            text: 'Down histo'
            size_hint_y: None
            height: '28dp'
            disabled: False
            on_release: root.downloadHisto()
    GridLayout: # enable to hide or display 'Del histo' menu item
        id: gridlayout_changePlaylist
		cols: 1
        size_hint_y: None
        height: "0dp"
        Button:
            text: 'Chge playlst'
            size_hint_y: None
            height: '28dp'
            disabled: False
            on_release: root.moveAudioFileToOtherPlaylist()
    GridLayout: # enable to hide or display 'Settings' menu item
        id: gridlayout_settings
		cols: 1
        size_hint_y: None
        height: "0dp"
        Button:
            text: "Settings"
            size_hint_y: None
            height: '28dp'
            on_press: app.open_settings()
	Button:
		text: 'Help'
		size_hint_y: None
		height: '28dp'
		on_release: root.help()