#: import RecycleViewKivyBugFix gui.recycleviewkivybugfix.RecycleViewKivyBugFix

<LoadFileChooserPopup>: # sub-class of FileChooserPopup, which derives from
						# AbstractPopup, which derives from Popup
	popupBoxLayout: popup_boxlayout
	diskRecycleBoxLayout: disc_mem_RB_layout
	fileChooser: file_chooser
	pathList: path_mem_list
	gridLayoutPathField: grid_layout_path_field
	currentPathField: text_path_load
	loadButton: btn_load
	BoxLayout:
		orientation: 'vertical'
		BoxLayout:
			id: popup_boxlayout
			orientation: 'vertical'
			#size_hint_y: 0.17 # value for Windows 10
			#size_hint_y: 0.11 # value for Android tablet
			size_hint_y: 0.16 # value for Android smartphone
			RecycleViewKivyBugFix:  # sub-class of RecycleView. Fixes a Kivy bug which
			                        # sometimes causes an app failure when the first
			                        # selected item in a displayed list is the last item
				id: path_mem_list
				effect_cls: "ScrollEffect" # prevents overscrolling
				viewclass: 'SelectableLabelFileChooser'
				scroll_type: ['bars', 'content']
				scroll_wheel_distance: dp(114)
				bar_width: dp(10)
				scroll_y: 1 # 0 forces scrolling to list bottom after adding
							# an item, 1 forces scrolling to list top
				effect_cls: "ScrollEffect" # prevents overscrolling
				SelectableRecycleBoxLayoutFileChooser:
					id: disc_mem_RB_layout
					key_selection: 'selectable' # required so that 'selectable'
												# key/value can be added to
												# RecycleView data items
					default_size: None, dp(28)
					default_size_hint: 1, None
					size_hint_y: None
					height: self.minimum_height
					orientation: 'vertical'
					multiselect: False
					touch_multiselect: False
					spacing: dp(2)

		BoxLayout:
			orientation: 'vertical'

			FileChooserListView:
				id: file_chooser
				dirselect: True
				filters: ["!*.sys", "*.txt", "*.mp3"] # "!*.sys" avoids pywintypes.error: (32, 'GetFileAttributesEx'
								        			  # exception when clicking on C: list item
				on_selection: text_path_load.text = self.selection and self.selection[0] or ''

			GridLayout:
				id: grid_layout_path_field
				#size_hint_y: 0.023 # tablet
				#size_hint_y: 0.035 # smartphone
				size_hint_y: 0.12 # Windows
				cols: 2
				GridLayout:
					rows: 1
					TextInput:
						id: text_path_load
						font_size: '15sp'
						multiline: False
						readonly: True

			GridLayout:
				cols: 2
				size_hint_y: None
				height: '28dp'
				Button:
					text: "Cancel"
					on_release: root.cancel()
				Button:
					id: btn_load
					text: "Load"
					on_release: root.loadFile(file_chooser.path, file_chooser.selection)

<SaveFileChooserPopup>: # sub-class of FileChooserPopup, which derives from
						# AbstractPopup, which derives from Popup
	popupBoxLayout: popup_boxlayout
	diskRecycleBoxLayout: disc_mem_RB_layout
	fileChooser: file_chooser
	pathList: path_mem_list
	gridLayoutPathField: grid_layout_path_field
	currentPathField: path_name_text_input
	currentFileNameField: file_name_text_input
	loadAtStartChkBox: load_at_start_chk_box
	BoxLayout:
		orientation: 'vertical'
		BoxLayout:
			id: popup_boxlayout
			orientation: 'vertical'
			#size_hint_y: 0.17 # value for Windows 10
			#size_hint_y: 0.11 # value for Android tablet
			size_hint_y: 0.16 # value for Android smartphone
			RecycleViewKivyBugFix:  # sub-class of RecycleView. Fixes a Kivy bug which
			                        # sometimes causes an app failure when the first
			                        # selected item in a displayed list is the last item
				id: path_mem_list
				effect_cls: "ScrollEffect" # prevents overscrolling
				viewclass: 'SelectableLabelFileChooser'
				scroll_type: ['bars', 'content']
				scroll_wheel_distance: dp(114)
				bar_width: dp(10)
				scroll_y: 1 # 0 forces scrolling to list bottom after adding
							# an item, 1 forces scrolling to list top
				effect_cls: "ScrollEffect" # prevents overscrolling
				SelectableRecycleBoxLayoutFileChooser:
					id: disc_mem_RB_layout
					key_selection: 'selectable' # required so that 'selectable'
												# key/value can be added to
												# RecycleView data items
					default_size: None, dp(28)
					default_size_hint: 1, None
					size_hint_y: None
					height: self.minimum_height
					orientation: 'vertical'
					multiselect: False
					touch_multiselect: False
					spacing: dp(2)

		BoxLayout:
			orientation: 'vertical'

			FileChooserListView:
				id: file_chooser
				dirselect: True
				filters: ["!*.sys", "*.txt"] # "!*.sys" avoids pywintypes.error: (32, 'GetFileAttributesEx'
											 # exception when clicking on C: list item
				on_selection: root.handleSelection(self.selection)

			GridLayout:
				id: grid_layout_path_field
				#size_hint_y: 0.023 # tablet
				#size_hint_y: 0.035 # smartphone
				size_hint_y: 0.30 # Windows
				cols: 2
				GridLayout:
					rows: 2
					TextInput:
						id: path_name_text_input
						font_size: '15sp'
						multiline: False
						readonly: False
						on_text: root.updateLoadAtStartCheckBox()
					TextInput:
						id: file_name_text_input
						font_size: '15sp'
						multiline: False
						readonly: False
						on_text: root.updateLoadAtStartCheckBox()
				CheckBox:
					id: load_at_start_chk_box
					#size_hint_x: 0.17 # smartphone
					size_hint_x: 0.06 # tablet, Windows
					on_press: root.toggleLoadAtStart(self.active)

			GridLayout:
				cols: 2
				size_hint_y: None
				height: '28dp'
				Button:
					text: "Cancel"
					on_release: root.cancel()
				Button:
					text: "Save"
					on_release: root.save(path_name_text_input.text, file_name_text_input.text, load_at_start_chk_box.active)

<DeleteFileChooserPopup>:   # sub-class of FileChooserPopup, which derives from
							# AbstractPopup, which derives from Popup
	popupBoxLayout: popup_boxlayout
	diskRecycleBoxLayout: disc_mem_RB_layout
	fileChooser: file_chooser
	pathList: path_mem_list
	deleteButton: delete_button
	deletedFilesLabel: deleted_files_label
	BoxLayout:
		orientation: 'vertical'
		BoxLayout:
			id: popup_boxlayout
			orientation: 'vertical'
			#size_hint_y: 0.17 # value for Windows 10
			#size_hint_y: 0.11 # value for Android tablet
			size_hint_y: 0.16 # value for Android smartphone
			RecycleViewKivyBugFix:  # sub-class of RecycleView. Fixes a Kivy bug which
			                        # sometimes causes an app failure when the first
			                        # selected item in a displayed list is the last item
				id: path_mem_list
				effect_cls: "ScrollEffect" # prevents overscrolling
				viewclass: 'SelectableLabelFileChooser'
				scroll_type: ['bars', 'content']
				scroll_wheel_distance: dp(114)
				bar_width: dp(10)
				scroll_y: 1 # 0 forces scrolling to list bottom after adding
							# an item, 1 forces scrolling to list top
				effect_cls: "ScrollEffect" # prevents overscrolling
				SelectableRecycleBoxLayoutFileChooser:
					id: disc_mem_RB_layout
					key_selection: 'selectable' # required so that 'selectable'
												# key/value can be added to
												# RecycleView data items
					default_size: None, dp(28)
					default_size_hint: 1, None
					size_hint_y: None
					height: self.minimum_height
					orientation: 'vertical'
					multiselect: False
					touch_multiselect: False
					spacing: dp(2)

		BoxLayout:
			orientation: 'vertical'

			FileChooserIconView: # FileChooserListView does not display multi selected files !
				id: file_chooser
				multiselect: True
				filters: ["!*.sys", "*.mp3"] # "!*.sys" avoids pywintypes.error: (32, 'GetFileAttributesEx'
											 # exception when clicking on C: list item
				dirselect: True # if True, the on_selection linked method is called
				                # when selecting a directory
				on_selection: root.handleSelection(self.selection)

			GridLayout:
				id: grid_layout_path_field
				#size_hint_y: 0.023 # tablet
				#size_hint_y: 0.035 # smartphone
				size_hint_y: 0.52 # Windows
				cols: 1
				ScrollView:
					id: scrlv_deleted_files
					canvas.before:
						Color:
							rgb: [0,0,0]
						Rectangle:
							pos: self.pos
							size: self.size
					effect_cls: "ScrollEffect" #prevents overscrolling
					#scroll_y: 0 # forces scrolling to bottom after adding text. Works only on TextInput, not on Label !!!
					do_scroll_x: False # limiting to vertical scrolling
					do_scroll_y: True

					Label:
						id: deleted_files_label
						size_hint_y: None
						height: self.texture_size[1]
			#			size_hint: (1, None)
			#			height: max(self.minimum_height, scrlv_out.height) #required to enable scrolling when output starts to grow
						text_size: (self.width-20), None
						# max_lines: 1000 no effect !
						line_height: 0.9
						background_color: 0,0,0,0
						foreground_color: 1,1,1,1
						valign: "top"
						markup: True

			GridLayout:
				cols: 3
				size_hint_y: None
				height: '28dp'
				Button:
					text: "Cancel"
					on_release: root.cancel()
				Button:
					text: "Unselect all"
					on_release: root.unselectAll()
				Button:
				    id: delete_button
					text: "Delete"
					disabled: True
					on_release: root.delete()

<SelectOrCreateDirFileChooserPopup>: # sub-class of FileChooserPopup, which derives from
									 # AbstractPopup, which derives from Popup
	popupBoxLayout: popup_boxlayout
	diskRecycleBoxLayout: disc_mem_RB_layout
	fileChooser: file_chooser
	pathList: path_mem_list
	gridLayoutPathField: grid_layout_path_field
	currentPathField: path_name_text_input
	currentFileNameField: file_name_text_input
	BoxLayout:
		orientation: 'vertical'
		BoxLayout:
			id: popup_boxlayout
			orientation: 'vertical'
			#size_hint_y: 0.17 # value for Windows 10
			#size_hint_y: 0.11 # value for Android tablet
			size_hint_y: 0.16 # value for Android smartphone
			RecycleViewKivyBugFix:  # sub-class of RecycleView. Fixes a Kivy bug which
			                        # sometimes causes an app failure when the first
			                        # selected item in a displayed list is the last item
				id: path_mem_list
				effect_cls: "ScrollEffect" # prevents overscrolling
				viewclass: 'SelectableLabelFileChooser'
				scroll_type: ['bars', 'content']
				scroll_wheel_distance: dp(114)
				bar_width: dp(10)
				scroll_y: 1 # 0 forces scrolling to list bottom after adding
							# an item, 1 forces scrolling to list top
				effect_cls: "ScrollEffect" # prevents overscrolling
				SelectableRecycleBoxLayoutFileChooser:
					id: disc_mem_RB_layout
					key_selection: 'selectable' # required so that 'selectable'
												# key/value can be added to
												# RecycleView data items
					default_size: None, dp(28)
					default_size_hint: 1, None
					size_hint_y: None
					height: self.minimum_height
					orientation: 'vertical'
					multiselect: False
					touch_multiselect: False
					spacing: dp(2)

		BoxLayout:
			orientation: 'vertical'

			FileChooserListView:
				id: file_chooser
				dirselect: True
				filters: [lambda folder, filename: not filename.endswith('')]
				on_selection: root.handleSelection(self.selection)

			GridLayout:
				id: grid_layout_path_field
				#size_hint_y: 0.023 # tablet
				#size_hint_y: 0.035 # smartphone
				size_hint_y: 0.30 # Windows
				cols: 2
				GridLayout:
					rows: 2
					TextInput:
						id: path_name_text_input
						font_size: '15sp'
						multiline: False
						readonly: False
						on_text: root.formatCurrentPathField()
					TextInput:
						id: file_name_text_input
						font_size: '15sp'
						multiline: False
						readonly: False
						on_text: root.updateCurrentFileNameField()

			GridLayout:
				cols: 2
				size_hint_y: None
				height: '28dp'
				Button:
					text: "Cancel"
					on_release: root.cancel()
				Button:
					text: "Select or create dir"
					on_release: root.selOrCreateDir(path_name_text_input.text, file_name_text_input.text)

<SelectableLabelFileChooser>:
	# Draw a background to indicate selection
	canvas.before:
		Color:
			rgba: (1, 0, 0, 1) if self.selected else (.0, 0.9, .1, .3)
		Rectangle:
			pos: self.pos
			size: self.size
		Color:
			rgba: (0, 0.9, .1, .3)
		Rectangle:
			pos: self.pos
			size: self.size
