<YesNoPopup>: # sub-class of GridLayout
	editableTextInput: txt_input_multiline
	cols:1
	rows: 2
	GridLayout:
	    id: grd
		cols: 1
		size_hint_y: None
		height: (len(txt_input_multiline._lines)+1) * txt_input_multiline.line_height
		GridLayout:
			cols: 1
			size_hint_x: 0.93
			TextInput:
				id: txt_input_multiline
				background_color: [0,0,0,1]
				foreground_color: [1,1,1,1]
				size_hint_y: 1 # solving problem of displaying partially multiline playlist title
				#text: root.text
				text: 'title'
				readonly: True
	GridLayout:
		cols: 4
		size_hint_y: None
		height: '28dp'
		Button:
			text: 'No'
			on_release: root.dispatch('on_answer', 'no')
		Button:
			text: 'Yes'
			on_release: root.dispatch('on_answer','yes')
