import os

DATE_TIME_FORMAT_VIDEO_INFO_FILE = '%d/%m/%Y %H:%M:%S'
RV_LIST_ITEM_SPACING_ANDROID = 2
RV_LIST_ITEM_SPACING_WINDOWS = 0.5

MSG_TYPE_STOP_DOWNLOADING = 1
MSG_TYPE_ATTRIBUTE_ERROR_VIDEO_TITLE = 2
MSG_TYPE_DISPLAY_RETRY_DOWNLOAD = 3
MSG_TYPE_AUDIO_ALREADY_DOWNLOADED_SAME_FILE_NAME = 4
MSG_TYPE_AUDIO_ALREADY_DOWNLOADED_DIFF_FILE_NAME = 5